class LanguageTexts {
  static const Map<String, String> english = {
    'greeting': 'Hello,\nGood Morning!',
    'no_messages': 'No Messages Yet!',
    'how_can_i_help': 'How can I help you..?',
    'photo_library': 'Photo Library',
    'explore_categories': 'Explore Categories',
    'see_all': 'See All',
    'hi_how_can_i_help': 'Hi, how can I help you today?',
    'create_image': 'I can create any image for you!',
    'select_language': 'Select Language',
    'back': 'Back',
    'next': 'Next',
    'activate_notifications': 'Activate Notifications',
    'night_mode': 'Night Mode',
    'change_language': 'Change Language',
    'welcome_message':
        'Welcome to the PEN AI application.\nThis app was developed by Abubaker Sallam, offering the ability to chat with the ChatGPT model to generate texts, images, and many other features.',
    'good_morning': 'Good morning, how can I help you today?',
    'voice': 'voice chatting with AI',
    'chat': 'chatting with AI',
    'images': 'create images with AI',
    'textdetuction': 'detecte texts from your images',
    'pdf': 'generate Q&A from your PDF',
  };

  static const Map<String, String> spanish = {
    'greeting': '¡Hola!,\nGood Morning',
    'no_messages': '¡Sin mensajes todavía!',
    'how_can_i_help': '¿Cómo puedo ayudarte..?',
    'photo_library': 'Biblioteca de fotos',
    'explore_categories': 'Explorar categorías',
    'see_all': 'Ver todo',
    'hi_how_can_i_help': 'Hola, ¿cómo puedo ayudarte hoy?',
    'create_image': 'Puedo crear cualquier imagen para ti!',
    'select_language': 'Seleccionar idioma',
    'back': 'Atrás',
    'next': 'Siguiente',
    'activate_notifications': 'Activar notificaciones',
    'night_mode': 'Modo nocturno',
    'change_language': 'Cambiar idioma',
    'welcome_message': 'Bienvenido a nuestra aplicación.',
    'good_morning': '¡Buenos días!, ¿cómo puedo ayudarte hoy?',
    'voice': 'chat de voz con IA',
    'chat': 'charlar con IA',
    'images': 'crear imágenes con IA',
    'textdetection': 'detectar textos en tus imágenes',
    'pdf': 'generar preguntas y respuestas desde tu PDF',
  };

  static const Map<String, String> arabic = {
    'greeting': 'مرحبا\nصباح الخير!',
    'no_messages': 'لا توجد رسائل بعد!',
    'how_can_i_help': 'كيف يمكنني مساعدتك؟',
    'photo_library': 'مكتبة الصور',
    'explore_categories': ' الفئات',
    'see_all': 'اظهار الكل',
    'hi_how_can_i_help': 'مرحبًا، كيف يمكنني مساعدتك اليوم؟',
    'create_image': 'يمكنني إنشاء أي صورة لك!',
    'select_language': 'اختر اللغة',
    'back': 'العودة',
    'next': 'التالي',
    'activate_notifications': 'تفعيل الإشعارات',
    'night_mode': 'الوضع الليلي',
    'change_language': 'تغيير اللغة',
    'welcome_message':
        'مرحبًا بك في تطبيق PEN AI\nهذا التطبيق تم تطويره بواسطة Abubaker Sallam، يقدم التطبيق إمكانية التحدث مع نموذج ChatGPT لتوليد نصوص، صور، والعديد من الميزات الأخرى.',
    'good_morning': 'صباح الخير، كيف يمكنني مساعدتك اليوم؟',
    'voice': 'الدردشة بالصوت مع الذكاء الاصطناعي',
    'chat': 'الدردشة مع الذكاء الاصطناعي',
    'images': 'إنشاء صور مع الذكاء الاصطناعي',
    'textdetection': 'اكتشاف النصوص في صورك',
    'pdf': 'إنشاء أسئلة وأجوبة من ملف PDF الخاص بك',
  };
}
